### ISSUE TITLE
Programo kraŝas je neenigo de nomo

### ISSUE THREAD

**Issue by LaPingvino** [batisteo/muskapti#1]
Bonvenon ĉe "Kaptu la muson"!
La celo de la ludo estas diveni numeron de 1 ĝis 100.
Vi povas provi tion unu post la alia.
Tamen atentu! La numero povas post ĉies vico ĉu 1 supreniri, ĉu tiom malsupreniri, ĉu resti sama.
Se la numero fariĝas pli alta ol 100, ĝi reiras al 1.
Se la numero fariĝas malpli alta ol 1, ĝi reiras al 100.
Multan sukceson!

Nomo de la 1a ludanto: 
Traceback (most recent call last):
  File "muskapti.py", line 108, in <module>
    nb_ludoj = rulu_ludon(ludantoj, min, max, rapideco)
  File "muskapti.py", line 99, in rulu_ludon
    venkulo, nb_provoj = ludu(ludantoj, min, max, rapideco)
  File "muskapti.py", line 78, in ludu
    nomo = ludantoj[vico % len(ludantoj)]
ZeroDivisionError: integer division or modulo by zero

**Comment by blfpd** [comment]
Dankon @LaPingvino !
